# Generated by Django 5.0 on 2023-12-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_alter_faculty_department_alter_faculty_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.CharField(choices=[('B.TECH', 'Bachelor of Technology'), ('M.TECH', 'Masters of Technology'), ('MBA', 'Master of Business Administration')], default='B.TECH', max_length=50),
            preserve_default=False,
        ),
    ]
